### ISSUE TITLE
meta_data()

### ISSUE THREAD

**Issue by wesselhuising** [J535D165/cbsodata#1]
Seems to be offline, or not working anymore. I guess they updated the syntax?

**Comment by J535D165** [comment]
Hello Wessel, ``meta_data`` is not a function in this library. Are you looking for the function ``get_info``? All public available function are listed here: http://cbsodata.readthedocs.io/en/latest/reference.html

Can you give me a small example of your code?

Jonathan

**Comment by J535D165** [comment]
Any updates on this? I can't reproduce it. 

Close?
