### ISSUE TITLE
 ModuleNotFoundError: No module named 'cbsodata.cbsodata3'

### ISSUE THREAD

**Issue by zufanka** [J535D165/cbsodata#10]
I have installed the package through pip, but when I want to import it I get 
`ModuleNotFoundError: No module named 'cbsodata.cbsodata3'`

version: 1.2

**Comment by J535D165** [comment]
Oei. Will work on a fix tonight. Please install version 1.1 (`pip install cbsodata==1.1`)

**Comment by J535D165** [comment]
Thanks for reporting, problems resolved in 1.2.2. Now available on PyPI
