### ISSUE TITLE
cbsodata does not work with python 3.8 and later

### ISSUE THREAD

**Issue by ericjanbelier** [J535D165/cbsodata#17]
cbsodata does not seem to work with python 3.8 or later

**Comment by J535D165** [comment]
Thanks for reporting. I think it is an issue with Python 3.9. I made a new release (1.3.3). Hopefully, this resolves your issues. Please let me know.

**Comment by ericjanbelier** [comment]
Thanks for the update. I am still getting the same error however. When i run it with Python 3.7.9 it works fine, but when i run it with 3.83 or 3.9 it stops without finishing properly. 

#Update:
I am using a Jupyter Notebook. I think that causes the problem. When using Idle it works fine. For some reason in jupyterlab The kernel justs stops running. 

I think in your code in optionsmanager the kernel stops running around here:

def __setattr__(self, arg, value):
        try:
            old_value = copy.copy(getattr(self, arg))
        except Exception:
            old_value = "undefined"

        self._log_setting_change(arg, old_value, value)
        super(OptionsManager, self).__setattr__(arg, value)

when a call is made to:
options = OptionsManager()

**Comment by J535D165** [comment]
Strange, because tests don't fail. 

Can you paste the output here and provide your OS?

Are you using Pycharm? So many issues with Pycharm (see other issue)

**Comment by SNR20db** [comment]
This issue has **probably** nothing to do with the API itself but `numpy.py`. I was trying to pull out data over with python3.9 and I got the same error. A sanity check there implying a call to `fmod()` fails due a slightly recent Windows update release.  I've just temporarily commented the call that involves `fmod()` to be called in `numpy` module and the sanity check succeeds (after all is just a sanity check). This module is working fine on Python3.9.(last version) at least for me! 

This issue mustn't foil you when using Python 32-bit.
[https://tinyurl.com/y3dm3h86](https://tinyurl.com/y3dm3h86)

**Comment by J535D165** [comment]
Thanks @SNR20db, this sounds reasonable. The numpy/Windows issues affect thousands of developers at the moment. Numpy is not a dependency of cbsodata, however it is a dependency of pandas. 

The issues with numpy and Windows will be resolved by the end of January I think. For now, there is nothing we can do I think. I'm closing the issue. Feel free to reopen or drop a message here.
