### ISSUE TITLE
Support for dataderden.cbs.nl URI's

### ISSUE THREAD

**Issue by jpvandervelden** [J535D165/cbsodata#6]
Hi,

Great library to retrieve the CBS data. All tables use this base URI: https://opendata.cbs.nl/ODataApi

CBS also creates solutions for third parties like MKB Nederland. These use the same API, but use another URI, for instance: https://dataderden.cbs.nl/ODataApi/odata/48034NED 
Could the library be enhanced to cater for these URI's?

Kind regards,

Jan-Paul.

**Comment by jpvandervelden** [comment]
Ah.. I see https://github.com/J535D165/cbsodata/issues/3 touches on this..

**Comment by J535D165** [comment]
Thanks Jan-Paul, good luck with your project. I will add some documentation on this.

**Comment by J535D165** [comment]
Hey Jan-Paul, I decided to add a few new methods to access dataderden. The method described in #3 is no longer the preferred way to access dataderden in V1.1 (2018-12-02). Check the README for the instructions.
